name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: thevanshit
          template: classic
          base: header, activity, community, repositories, metadata

          config_display: compact
          config_padding: 14%
          config_timezone: Asia/Calcutta

          repositories_forks: yes
          repositories_affiliations: owner, collaborator

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_display: compact
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_threshold: 1%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

