name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Basic sections
          user: thevanshit
          template: classic
          base: header, activity, community, repositories

          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage

          # Contribution stats
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes

          # Issues & PRs
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_discussions: yes
          plugin_topics: yes

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes

          # Streaks
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

          # Skyline (3D graph)
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1

          # Output
          filename: github-metrics.svg
